name       : haskell-monad-control
version    : 1.0.1.0
release    : 1
source     :
    - http://hackage.haskell.org/package/monad-control-1.0.1.0/monad-control-1.0.1.0.tar.gz : d4b0209c6cb7006fac618e4d8e3743d908f8b21579d6ff72e9f6e758e24301f4
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package defines the type class MonadBaseControl
description: |
    This package defines the type class MonadBaseControl, a subset of MonadBase into which generic control operations such as catch can be lifted from IO or any other base monad. Instances are based on monad transformers in MonadTransControl, which includes all standard monad transformers in the transformers library except ContT.
builddeps  :
    - haskell-cabal-install
    - haskell-transformers-base
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register